# Generated by Django 4.1.1 on 2022-12-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0009_cars_cost_of_vehicle_cars_rent_per_hour_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="subscription",
            field=models.CharField(default="1", max_length=6),
        ),
    ]
