# Generated by Django 4.1.1 on 2022-12-06 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("booking", "0010_rename_user_id_book_car_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("owner", "0009_cars_cost_of_vehicle_cars_rent_per_hour_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_date", models.DateTimeField()),
                ("to_date", models.DateTimeField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "book_car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.book_car",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="owner.cars"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
