# Generated by Django 4.1.1 on 2022-12-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0002_book_confirmation"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
